[package]
name = "basalt-widgets"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
# basalt = { git = "https://github.com/AustinJ235/basalt.git", rev = "e8d2955" }
basalt = { path = "../basalt" }
parking_lot = "0.12"
