[package]
name = "basalt-widgets"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
# basalt = { git = "https://github.com/AustinJ235/basalt.git", rev = "1d9d32d" }
basalt = { path = "../basalt", features = ["deadlock_detection"] }
parking_lot = "0.12"
