[package]
name = "basalt-widgets"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
basalt = { git = "https://github.com/AustinJ235/basalt.git", rev = "ed01b2a6bb89ac3720527f322aec39cd9d468852" }
# basalt = { path = "../basalt" }
parking_lot = "0.12"
