[package]
name = "basalt-widgets"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
basalt = { git = "https://github.com/AustinJ235/basalt.git", rev = "85cf6e41e424007bfe5e7fbdd3858c5ac24b05f3" }
parking_lot = "0.12"
