[package]
name = "basalt-widgets"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
# basalt = { git = "https://github.com/AustinJ235/basalt.git", rev = "ef2973b" }
basalt = { path = "../basalt" }
parking_lot = "0.12"
